stages:
  - test
  - build

# .go_template:
#   image: golang:latest
#   before_script:
#     - make download

# .docker_template:
#   image: docker:stable
#   services:
#     - docker:dind
#   before_script:
#     - apk add git
#     - apk add make
#     - docker login -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD $CI_REGISTRY

dependencies:
  stage: test
  script:
    - make check/dependencies

format:
  stage: test
  script:
    - make check/fmt

test:
  stage: test
  script:
    - make test

build:
  stage: build
  script:
    - make build

# build:
#   extends: .go_template
#   stage: build
#   only:
#     - main
#     - tags
#   script:
#     - git fetch --tags
#     - make build/snapshot
#   artifacts:
#     paths:
#       - dist/*.tar.gz
#       - dist/checksums.txt
#     expire_in: 1 day

# docker/gitlab:
#   extends: .docker_template
#   stage: build
#   only:
#     - tags
#   script:
#     - make docker/build/latest
#     - make docker/build/tag
#     - docker push registry.gitlab.com/hectorjsmith/fail2ban-prometheus-exporter

# docker/gitlab/nightly:
#   extends: .docker_template
#   stage: build
#   only:
#     - main
#   script:
#     - make docker/build/nightly
#     - docker push registry.gitlab.com/hectorjsmith/fail2ban-prometheus-exporter
